### ISSUE TITLE
[refactoring] Docker 적용 - Celery

### ISSUE THREAD

**Issue by YuJinsoo** [I-deul-of-zoo/foodie-hotspot-recommendation-service#65]
기존 APScheduler로 구현한 스케쥴러 -> Celery worker + Celery beat로 구현한 부분을 docker 환경으로 구현.

**Comment by tneoeo2** [comment]
`docker-compose.yml` 에 worker와 beat 관련 설정을 추가하였습니다.
```
  celery-restaurant-worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: celery-restaurant-worker
    environment:
      - BROKER_URL ="redis://${REDIS_HOST}:6379"
      - RESULT_BACKEND ="redis://${REDIS_HOST}:6379"
    volumes:
      - .:/app
    command: celery -A config worker --loglevel=INFO -Q worker1@%h  #worker 실행명령어
    depends_on:
      - mysql
      - redis
      - django
    restart: always

  celery-discord-worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: celery-discord-worker
    environment:
      - BROKER_URL = "redis://${REDIS_HOST}:6379"
      - RESULT_BACKEND = "redis://${REDIS_HOST}:6379"
    volumes:
      - .:/app
    command: celery -A config worker --loglevel=INFO -Q worker2@%h   #worker 실행명령어
    depends_on:
      - mysql
      - redis
      - django
    restart: always

  celery-beat:
    build:
      context: .
      dockerfile: ./Dockerfile  
    container_name: celery-beat
    environment:
      - BROKER_URL = "redis://${REDIS_HOST}:6379"
      - RESULT_BACKEND = "redis://${REDIS_HOST}:6379"
    volumes:
      - .:/app
    command: celery -A config beat
    depends_on:
      - mysql
      - redis
      - django
    restart: always
```
터미널에서  `docker compose up`시  worker 실행됨을 확인하였으나 settings.py에 설정된 시간에 worker가 동작하지않음
